# Generated by Django 5.0.2 on 2025-03-27 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainings', '0006_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveTrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Activo'), ('paused', 'Pausado'), ('completed', 'Completado')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('trainer_notes', models.TextField(blank=True)),
                ('student_notes', models.TextField(blank=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.training')),
            ],
        ),
        migrations.CreateModel(
            name='LiveSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('reps', models.IntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('trainer_feedback', models.TextField(blank=True)),
                ('form_rating', models.IntegerField(blank=True, null=True)),
                ('perceived_effort', models.IntegerField(blank=True, null=True)),
                ('completed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.set')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_sets', to='trainers.livetrainingsession')),
            ],
        ),
        migrations.CreateModel(
            name='TrainerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=100, verbose_name='Especialización')),
                ('experience_years', models.IntegerField(default=0, verbose_name='Años de experiencia')),
                ('certification', models.CharField(blank=True, max_length=200, verbose_name='Certificación')),
                ('bio', models.TextField(blank=True, verbose_name='Biografía')),
                ('active', models.BooleanField(default=True, verbose_name='Activo')),
                ('max_students', models.IntegerField(default=10, verbose_name='Máximo de estudiantes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Entrenador',
                'verbose_name_plural': 'Perfiles de Entrenadores',
            },
        ),
        migrations.CreateModel(
            name='TrainerStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_relationships', to=settings.AUTH_USER_MODEL)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('trainer', 'student')},
            },
        ),
        migrations.CreateModel(
            name='TrainerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainings.training')),
                ('trainer_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainerstudent')),
            ],
        ),
        migrations.AddField(
            model_name='livetrainingsession',
            name='trainer_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainerstudent'),
        ),
    ]
