# Generated by Django 5.0.2 on 2025-03-27 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=200, verbose_name='Ejercicio')),
                ('sets_count', models.IntegerField(default=3, verbose_name='Número de series')),
                ('reps', models.IntegerField(default=12, verbose_name='Repeticiones')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Peso (kg)')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('order', models.IntegerField(default=0, verbose_name='Orden')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Serie de ejercicio',
                'verbose_name_plural': 'Series de ejercicios',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='liveset',
            name='set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainerset'),
        ),
        migrations.CreateModel(
            name='TrainerTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('date', models.DateField(verbose_name='Fecha programada')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duración (minutos)')),
                ('completed', models.BooleanField(default=False, verbose_name='Completado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_trainings', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_trainings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rutina de entrenamiento',
                'verbose_name_plural': 'Rutinas de entrenamiento',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='trainerset',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='trainers.trainertraining'),
        ),
        migrations.AlterField(
            model_name='livetrainingsession',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainertraining'),
        ),
        migrations.AlterField(
            model_name='trainerfeedback',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainertraining'),
        ),
    ]
