# Generated by Django 5.0.2 on 2025-03-28 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_trainerset_alter_liveset_set_trainertraining_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainertraining',
            name='scheduled_days',
            field=models.CharField(blank=True, help_text='Días de la semana separados por comas', max_length=100, verbose_name='Días programados'),
        ),
    ]
