# Generated by Django 5.0.2 on 2025-03-28 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_trainertraining_scheduled_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainerset',
            name='training',
        ),
        migrations.RemoveField(
            model_name='trainertraining',
            name='scheduled_days',
        ),
        migrations.CreateModel(
            name='TrainerTrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20, verbose_name='Día de la semana')),
                ('focus', models.CharField(blank=True, max_length=255, null=True, verbose_name='Enfoque')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='trainers.trainertraining')),
            ],
            options={
                'verbose_name': 'Día de entrenamiento',
                'verbose_name_plural': 'Días de entrenamiento',
                'unique_together': {('training', 'day_of_week')},
            },
        ),
        migrations.AddField(
            model_name='trainerset',
            name='training_day',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sets', to='trainers.trainertrainingday'),
            preserve_default=False,
        ),
    ]
