# Generated by Django 5.0.2 on 2025-03-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0004_remove_trainerset_training_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainertrainingday',
            options={'ordering': [models.Case(models.When(day_of_week='Lunes', then=models.Value(1)), models.When(day_of_week='Martes', then=models.Value(2)), models.When(day_of_week='Miércoles', then=models.Value(3)), models.When(day_of_week='Jueves', then=models.Value(4)), models.When(day_of_week='Viernes', then=models.Value(5)), models.When(day_of_week='Sábado', then=models.Value(6)), models.When(day_of_week='Domingo', then=models.Value(7)), default=models.Value(10), output_field=models.IntegerField())]},
        ),
        migrations.AlterField(
            model_name='trainertrainingday',
            name='day_of_week',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=20),
        ),
        migrations.AlterField(
            model_name='trainertrainingday',
            name='focus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
