# Generated by Django 5.0.2 on 2025-03-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0005_alter_trainertrainingday_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='liveset',
            name='set_number',
            field=models.IntegerField(default=1),
        ),
    ]
