# Generated by Django 5.0.2 on 2025-03-31 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0006_liveset_set_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='livetrainingsession',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livetrainingsession',
            name='student_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
