# Generated by Django 5.0.2 on 2025-04-08 02:29

import django.db.models.deletion
from django.db import migrations, models

def convert_exercise_data(apps, schema_editor):
    TrainerSet = apps.get_model('trainers', 'TrainerSet')
    Exercise = apps.get_model('exercises', 'Exercise')
    
    # Crear un diccionario de nombres de ejercicios a instancias
    exercise_map = {ex.name: ex for ex in Exercise.objects.all()}
    
    # Actualizar cada TrainerSet
    for trainer_set in TrainerSet.objects.all():
        if trainer_set.exercise in exercise_map:
            trainer_set.exercise_id = exercise_map[trainer_set.exercise]
            trainer_set.save()

def reverse_convert(apps, schema_editor):
    TrainerSet = apps.get_model('trainers', 'TrainerSet')
    Exercise = apps.get_model('exercises', 'Exercise')
    
    # Crear un diccionario de IDs a nombres de ejercicios
    exercise_map = {ex.id: ex.name for ex in Exercise.objects.all()}
    
    # Actualizar cada TrainerSet
    for trainer_set in TrainerSet.objects.all():
        if trainer_set.exercise_id in exercise_map:
            trainer_set.exercise = exercise_map[trainer_set.exercise_id]
            trainer_set.save()

class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0018_remove_equipment_relation'),
        ('trainers', '0007_livetrainingsession_timer_started_at_and_more'),
    ]

    operations = [
        # Agregar el nuevo campo exercise_id
        migrations.AddField(
            model_name='trainerset',
            name='exercise_id',
            field=models.ForeignKey(
                'exercises.Exercise',
                on_delete=django.db.models.deletion.CASCADE,
                null=True,
                blank=True,
                verbose_name="Ejercicio ID"
            ),
        ),
        
        # Transferir los datos
        migrations.RunPython(
            convert_exercise_data,
            reverse_convert
        ),
        
        # Eliminar el campo antiguo
        migrations.RemoveField(
            model_name='trainerset',
            name='exercise',
        ),
        
        # Renombrar el nuevo campo
        migrations.RenameField(
            model_name='trainerset',
            old_name='exercise_id',
            new_name='exercise',
        ),
    ]
