# Generated by Django 5.0.2 on 2025-04-10 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0019_exercise_is_active'),
        ('trainers', '0008_alter_trainerset_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerset',
            name='exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Ejercicio'),
        ),
    ]
