# Generated by Django 5.0.2 on 2025-04-27 13:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0019_exercise_is_active'),
        ('trainers', '0009_alter_trainerset_exercise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainertraining',
            options={'ordering': ['-start_date', '-created_at'], 'verbose_name': 'Rutina de entrenamiento', 'verbose_name_plural': 'Rutinas de entrenamiento'},
        ),
        migrations.AlterModelOptions(
            name='trainertrainingday',
            options={'ordering': [models.Case(models.When(day_of_week='Lunes', then=models.Value(1)), models.When(day_of_week='Martes', then=models.Value(2)), models.When(day_of_week='Miércoles', then=models.Value(3)), models.When(day_of_week='Jueves', then=models.Value(4)), models.When(day_of_week='Viernes', then=models.Value(5)), models.When(day_of_week='Sábado', then=models.Value(6)), models.When(day_of_week='Domingo', then=models.Value(7)), default=models.Value(10), output_field=models.IntegerField())], 'verbose_name': 'Día de Entrenamiento', 'verbose_name_plural': 'Días de Entrenamiento'},
        ),
        migrations.RemoveField(
            model_name='trainertraining',
            name='date',
        ),
        migrations.AddField(
            model_name='trainerset',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='trainerset',
            name='rest_time',
            field=models.IntegerField(default=60, verbose_name='Tiempo de descanso (segundos)'),
        ),
        migrations.AddField(
            model_name='trainertraining',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AddField(
            model_name='trainertraining',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='trainertraining',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AddField(
            model_name='trainertrainingday',
            name='day_order',
            field=models.IntegerField(default=0, verbose_name='Orden del día'),
        ),
        migrations.AddField(
            model_name='trainertrainingday',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trainertrainingday',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notas del día'),
        ),
        migrations.AlterField(
            model_name='trainerset',
            name='reps',
            field=models.CharField(default='12', max_length=50, validators=[django.core.validators.RegexValidator('^\\d+(-\\d+)?$', 'Formato: número o rango (ej: 10-12)')], verbose_name='Repeticiones'),
        ),
        migrations.AlterField(
            model_name='trainerset',
            name='sets_count',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de series'),
        ),
        migrations.AlterField(
            model_name='trainerset',
            name='weight',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Formato: número decimal')], verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='trainertrainingday',
            name='focus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Enfoque'),
        ),
        migrations.CreateModel(
            name='TrainerTrainingExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Número de series')),
                ('reps', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\d+(-\\d+)?$', 'Formato: número o rango (ej: 10-12)')], verbose_name='Repeticiones')),
                ('weight', models.CharField(blank=True, max_length=50, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Formato: número decimal')], verbose_name='Peso sugerido')),
                ('rest_time', models.IntegerField(default=60, help_text='Tiempo de descanso en segundos')),
                ('exercise_order', models.IntegerField(default=0, verbose_name='Orden del ejercicio')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, verbose_name='Notas del ejercicio')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('training_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='trainers.trainertrainingday')),
            ],
            options={
                'verbose_name': 'Ejercicio de Entrenamiento',
                'verbose_name_plural': 'Ejercicios de Entrenamiento',
                'ordering': ['exercise_order'],
            },
        ),
        migrations.CreateModel(
            name='CompletedExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('actual_sets', models.IntegerField(verbose_name='Series realizadas')),
                ('actual_reps', models.CharField(max_length=50, verbose_name='Repeticiones realizadas')),
                ('actual_weight', models.CharField(blank=True, max_length=50, verbose_name='Peso utilizado')),
                ('notes', models.TextField(blank=True, verbose_name='Notas de la sesión')),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Duración en segundos')),
                ('difficulty', models.CharField(choices=[('Fácil', 'Fácil'), ('Moderado', 'Moderado'), ('Difícil', 'Difícil')], default='Moderado', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('training_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainers.trainertrainingexercise')),
            ],
            options={
                'verbose_name': 'Ejercicio Completado',
                'verbose_name_plural': 'Ejercicios Completados',
                'ordering': ['-completed_at'],
            },
        ),
    ]
