# Generated by Django 5.0.2 on 2025-04-27 13:08

from django.db import migrations
from django.utils import timezone

def clean_null_data(apps, schema_editor):
    """
    Limpia los datos nulos en los modelos:
    1. Actualiza start_date nulo usando created_at
    2. Elimina TrainerSet con exercise nulo
    3. Actualiza weight nulo a '0'
    4. Actualiza focus nulo a ''
    """
    TrainerTraining = apps.get_model('trainers', 'TrainerTraining')
    TrainerSet = apps.get_model('trainers', 'TrainerSet')
    TrainerTrainingDay = apps.get_model('trainers', 'TrainerTrainingDay')

    # 1. Actualizar start_date nulo usando created_at
    for training in TrainerTraining.objects.filter(start_date__isnull=True):
        training.start_date = training.created_at.date()
        training.save()

    # 2. Eliminar TrainerSet con exercise nulo
    TrainerSet.objects.filter(exercise__isnull=True).delete()

    # 3. Actualizar weight nulo a '0'
    TrainerSet.objects.filter(weight__isnull=True).update(weight='0')

    # 4. Actualizar focus nulo a ''
    TrainerTrainingDay.objects.filter(focus__isnull=True).update(focus='')

def reverse_clean_data(apps, schema_editor):
    """
    No es necesario revertir estos cambios ya que son limpieza de datos
    """
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0010_alter_trainertraining_options_and_more'),
    ]

    operations = [
        migrations.RunPython(clean_null_data, reverse_clean_data),
    ]
