# Generated by Django 5.0.2 on 2025-04-27 13:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0019_exercise_is_active'),
        ('trainers', '0011_auto_20250427_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainerset',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise', verbose_name='Ejercicio'),
        ),
        migrations.AlterField(
            model_name='trainerset',
            name='weight',
            field=models.CharField(blank=True, default='0', max_length=50, validators=[django.core.validators.RegexValidator('^\\d+(\\.\\d+)?$', 'Formato: número decimal')], verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='trainertraining',
            name='start_date',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='trainertrainingday',
            name='focus',
            field=models.CharField(blank=True, max_length=255, verbose_name='Enfoque'),
        ),
    ]
