# Generated by Django 5.0.2 on 2025-03-22 03:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='training',
            name='calories_burned',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 3, 22, 3, 2, 38, 668282, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='day_of_week',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='training',
            name='duration',
            field=models.IntegerField(blank=True, help_text='Duración total en minutos', null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='intensity',
            field=models.CharField(choices=[('Ligero', 'Ligero'), ('Moderado', 'Moderado'), ('Intenso', 'Intenso'), ('Muy Intenso', 'Muy Intenso')], default='Moderado', max_length=20),
        ),
        migrations.AddField(
            model_name='training',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='training',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='recurring_days',
            field=models.CharField(blank=True, help_text='Días de la semana separados por comas', max_length=100),
        ),
        migrations.AddField(
            model_name='training',
            name='reps',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='training',
            name='rest_time',
            field=models.IntegerField(default=60, help_text='Tiempo de descanso entre series en segundos'),
        ),
        migrations.AddField(
            model_name='training',
            name='sets',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='training',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
