# Generated by Django 5.0.2 on 2025-03-26 01:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_equipment_exercise_instructions_and_more'),
        ('trainings', '0002_alter_training_options_training_calories_burned_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='training',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.RemoveField(
            model_name='training',
            name='sets',
        ),
        migrations.AddField(
            model_name='training',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='training',
            name='total_sets',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='training',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='training',
            name='day_of_week',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='training',
            name='reps',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='training',
            name='rest_time',
            field=models.IntegerField(default=90),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField()),
                ('weight', models.FloatField()),
                ('reps', models.IntegerField()),
                ('completed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exercises.exercise')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sets', to='trainings.training')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['training', 'set_number'],
                'unique_together': {('training', 'set_number')},
            },
        ),
    ]
