# Generated by Django 5.0.2 on 2025-03-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainings', '0003_alter_training_options_remove_training_sets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='set',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
