# Generated by Django 5.0.2 on 2025-04-12 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0009_alter_trainerset_exercise'),
        ('trainings', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='trainer_training',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_trainings', to='trainers.trainertraining'),
        ),
    ]
