# Generated by Django 5.0.2 on 2025-04-28 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0019_exercise_is_active'),
        ('trainings', '0007_training_trainer_training'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='set',
            options={'ordering': ['training', 'exercise', 'set_number']},
        ),
        migrations.AlterUniqueTogether(
            name='set',
            unique_together={('training', 'exercise', 'set_number')},
        ),
    ]
