# Generated by Django 5.0.2 on 2025-03-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_created_at_exercise_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('Pecho', 'Pecho'), ('Espalda', 'Espalda'), ('Piernas', 'Piernas'), ('Hombros', 'Hombros'), ('Brazos', 'Brazos'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Abdominales', 'Abdominales'), ('Core', 'Core'), ('Cardio', 'Cardio'), ('Pierna Posterior', 'Pierna Posterior'), ('Tren Superior', 'Tren Superior')], max_length=20),
        ),
    ]
