# Generated by Django 5.0.2 on 2025-03-30 21:53

import gym_tracker.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_auto_20250329_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=gym_tracker.storage_backend.GymStorage(), upload_to='exercises', verbose_name='Imagen del ejercicio'),
        ),
    ]
