# Generated by Django 5.0.2 on 2025-03-30 22:05

import django.db.models.deletion
import gym_tracker.exercises.models
import gym_tracker.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0007_exercise_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='youtube_link',
            field=models.URLField(blank=True, help_text='Ingresa la URL del video de YouTube que muestra cómo realizar el ejercicio', max_length=255, null=True, verbose_name='Link de YouTube'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.ForeignKey(default=gym_tracker.exercises.models.ExerciseCategory.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exercises', to='exercises.exercisecategory', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')], max_length=20, verbose_name='Dificultad'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Equipamiento'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=gym_tracker.storage_backend.GymStorage(), upload_to='exercises', verbose_name='Imagen del ejercicio (JPG, PNG o GIF)'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='instructions',
            field=models.TextField(blank=True, null=True, verbose_name='Instrucciones'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primary_muscles',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Músculos principales'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Músculos secundarios'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='tips',
            field=models.TextField(blank=True, null=True, verbose_name='Consejos'),
        ),
    ]
