# Generated by Django 5.0.2 on 2025-03-31 01:20

from django.db import migrations, models
import django.db.models.deletion

def forwards_func(apps, schema_editor):
    Exercise = apps.get_model("exercises", "Exercise")
    Equipment = apps.get_model("exercises", "Equipment")
    
    # Crear equipamiento por defecto
    default_equipment, _ = Equipment.objects.get_or_create(name="Sin equipamiento")
    
    # Crear un diccionario para mapear nombres a objetos Equipment
    equipment_dict = {}
    
    # Iterar sobre todos los ejercicios y crear Equipment según sea necesario
    for exercise in Exercise.objects.all():
        equipment_name = exercise.equipment
        if not equipment_name or not isinstance(equipment_name, str):
            equipment_name = "Sin equipamiento"
        
        if equipment_name not in equipment_dict:
            equipment, _ = Equipment.objects.get_or_create(name=equipment_name)
            equipment_dict[equipment_name] = equipment
        
        # Guardar el ID del equipment en el campo temporal
        exercise.new_equipment_id = equipment_dict[equipment_name].id
        exercise.save()

def reverse_func(apps, schema_editor):
    Exercise = apps.get_model("exercises", "Exercise")
    for exercise in Exercise.objects.all():
        if hasattr(exercise, 'new_equipment'):
            exercise.equipment = exercise.new_equipment.name
            exercise.save()

class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0009_equipment_alter_exercise_equipment'),
    ]

    operations = [
        # Añadir campo temporal
        migrations.AddField(
            model_name='exercise',
            name='new_equipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='exercises.equipment'),
        ),
        
        # Ejecutar la función de conversión de datos
        migrations.RunPython(forwards_func, reverse_func),
        
        # Eliminar el campo original
        migrations.RemoveField(
            model_name='exercise',
            name='equipment',
        ),
        
        # Renombrar el campo nuevo
        migrations.RenameField(
            model_name='exercise',
            old_name='new_equipment',
            new_name='equipment',
        ),
        
        # Configurar el campo final
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.SET_DEFAULT,
                default=1,  # ID del equipamiento por defecto
                related_name='exercises',
                to='exercises.equipment',
                verbose_name='Equipamiento'
            ),
        ),
    ] 