# Generated by Django 5.0.2 on 2025-03-31 15:48

import django.db.models.deletion
import gym_tracker.exercises.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0010_convert_equipment_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.ForeignKey(default=gym_tracker.exercises.models.Equipment.get_default_pk, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exercises', to='exercises.equipment', verbose_name='Equipamiento'),
        ),
    ]
