# Generated by Django 5.0.2 on 2025-03-31 22:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_alter_exercise_equipment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name'], 'verbose_name': 'Ejercicio', 'verbose_name_plural': 'Ejercicios'},
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='youtube_link',
        ),
        migrations.AddField(
            model_name='exercise',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_group',
            field=models.CharField(choices=[('chest', 'Pecho'), ('back', 'Espalda'), ('shoulders', 'Hombros'), ('arms', 'Brazos'), ('legs', 'Piernas'), ('core', 'Core'), ('full_body', 'Cuerpo completo'), ('cardio', 'Cardio')], default='arms', max_length=20, verbose_name='Grupo muscular'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL del video'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Principiante'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='intermediate', max_length=20, verbose_name='Dificultad'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment',
            field=models.CharField(blank=True, max_length=100, verbose_name='Equipamiento'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='exercises/', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='primary_muscles',
            field=models.CharField(blank=True, default='No especificado', max_length=100, verbose_name='Músculos principales'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.CharField(blank=True, default='No especificado', max_length=100, verbose_name='Músculos secundarios'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ExerciseImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='exercises/gallery/', verbose_name='Imagen')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Leyenda')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Orden')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='exercises.exercise', verbose_name='Ejercicio')),
            ],
            options={
                'verbose_name': 'Imagen de ejercicio',
                'verbose_name_plural': 'Imágenes de ejercicios',
                'ordering': ['order'],
            },
        ),
    ]
