# Generated by Django 5.0.4 on 2025-03-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role_traineruser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='altura',
            field=models.FloatField(blank=True, help_text='Altura en centímetros', null=True),
        ),
    ]
