# Generated by Django 5.0.2 on 2025-03-25 17:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_altura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traineruser',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
